/**
 * /writeup/ is the canonical long-form article about the ideas, history, and
 * implementation behind VeryGoodWallet. It is written for a curious technical
 * reader with no cryptography background; deeper detail lives in set-off
 * asides and in the three annotated "anatomy" figures, whose specimens were
 * generated by running the demo's real issuance and presentation stack.
 */
import { CredentialAnatomy } from "./CredentialAnatomy";
import { PresentationCards, PresentationWire } from "./PresentationAnatomy";
import { Toc, type TocSection } from "./Toc";

const TOC_SECTIONS: readonly TocSection[] = [
  { id: "origins", label: "Where the idea came from" },
  { id: "pieces", label: "The pieces have caught up" },
  {
    id: "credential-and-wallet",
    label: "A credential and its wallet",
    children: [
      { id: "passkey-wallet", label: "Your passkey is the wallet" },
      { id: "credential-anatomy", label: "Anatomy of a credential" },
    ],
  },
  {
    id: "bbs",
    label: "BBS signatures, explained",
    children: [{ id: "holder-binding", label: "Whose credential is it?" }],
  },
  {
    id: "presentations",
    label: "What a presentation can prove",
    children: [
      { id: "linking", label: "Linking as a choice" },
      { id: "presentation-anatomy", label: "Anatomy of a presentation" },
      { id: "verifier-compare", label: "What verifiers can compare" },
    ],
  },
  { id: "revocation", label: "Privacy-preserving revocation" },
  { id: "browser", label: "The browser is part of the thesis" },
  { id: "standards", label: "How it fits existing standards" },
  { id: "real", label: "Real vs. experimental" },
  { id: "vision", label: "A vision I have carried" },
  { id: "colophon", label: "Colophon" },
];

export function Writeup() {
  return (
    // No items-start on the grid: the aside must stretch to full row height
    // so the sticky .toc inside it has room to travel.
    <div className="mx-auto max-w-6xl px-5 pb-24 lg:grid lg:grid-cols-[minmax(0,1fr)_13rem] lg:gap-12">
      <div className="min-w-0">
        <header className="mx-auto max-w-2xl pt-12">
          <a
            href="/"
            className="font-label text-[11px] uppercase tracking-[0.2em] text-stamp underline decoration-stamp/50 underline-offset-2 hover:decoration-stamp"
          >
            ← back to the cover
          </a>
          <h1 className="mt-6 font-display text-4xl font-bold leading-tight tracking-tight">
            VeryGoodWallet: the identity wallet I wanted to build years ago
          </h1>
          <p className="mt-4 text-[16px] leading-relaxed text-ink-dim">
            The story and technology behind a passkey-native identity wallet, an
            issuer, and two verifiers. The setting is fictional, but the protocols
            and cryptography are real. You do not need a background in
            zero-knowledge proofs to follow along, but there is enough detail here
            if you already have one.
          </p>
        </header>

        <article className="prose prose-shell mt-4">
          <h2 id="origins">Where the idea came from</h2>
          <p>
            I have been thinking about versions of this project for a long time.
            The idea goes back to what first excited me about decentralized
            identity and to the conversations that eventually led my two
            co-founders and me to start Trinsic.
          </p>
          <p>
            We met through the early decentralized identity community, at a
            conference where people were building and promoting technologies such
            as AnonCreds and the work happening around the Sovrin Foundation. The
            three of us shared a belief that people should have more control over
            how their identity information was held and used.
          </p>
          <p>
            The part of that vision that especially captured my imagination was
            the wallet. I was excited by the possibility that a person could hold
            trusted credentials, decide when to use them, and prove what was
            necessary without routinely handing over an entire identity document.
          </p>
          <p>
            That idea shaped our earliest work at Trinsic and stayed with me
            throughout the five years I spent there. We were able to explore
            important parts of it using the technologies available at the time,
            but several pieces that now feel essential were not ready yet.
          </p>
          <p>
            Passkeys did not exist. Key management was difficult. Credential
            issuance and presentation protocols were still developing.
            Browser-based cryptography came with significant practical
            constraints. Building the experience I imagined meant asking users
            and developers to carry much more complexity than I wanted.
          </p>
          <p>
            This particular question stayed with me: what should a private,
            user-controlled identity wallet actually feel like?
          </p>
          <p>
            VeryGoodWallet is my personal return to that question. It is not an
            attempt to recreate an earlier product or prescribe where identity
            technology should go. It is an exploration of what the wallet vision
            that originally excited me looks like with the technologies available
            now.
          </p>

          <h2 id="pieces">The pieces have caught up</h2>
          <p>
            Passkeys offer a practical foundation for wallet key management.
            OpenID for Verifiable Credential Issuance and OpenID for Verifiable
            Presentations provide much better plumbing between issuers, wallets,
            and verifiers. W3C Verifiable Credentials provide a recognizable
            document model for signed claims, and BBS signatures give us a strong
            cryptographic foundation for selective disclosure and freshly
            randomized presentations.
          </p>
          <p>
            Modern browsers have also become capable cryptographic runtimes. All
            of the cryptography on this site, including BBS signatures, range and
            membership proofs, cross-credential equality, and non-revocation
            proofs, runs in plain TypeScript on ordinary web infrastructure. There
            is no WASM, circuit compiler, proving key, or trusted setup.
          </p>
          <p>
            The individual pieces come from different parts of the identity, web,
            and cryptography communities. What interested me was whether they
            could now be pulled together into one coherent, browser-native
            experience.
          </p>

          <h2 id="credential-and-wallet">A credential and the wallet that holds it</h2>
          <p>
            A verifiable credential is a signed set of claims. An issuer, such as
            a DMV, university, or employer, signs those claims and gives the
            credential to you. Later, you show it to a verifier, who checks the
            signature with the issuer&apos;s public key. The verifier does not
            need to call the issuer, so the issuer never learns where you use the
            credential. The format is a W3C standard, and the demo&apos;s Utopia
            driver&apos;s license is a W3C Verifiable Credential.
          </p>

          <h3 id="passkey-wallet">Your passkey is the wallet</h3>
          <p>
            Before a credential can be held, something has to do the holding.
            Most identity wallets need a long-lived secret, and historically that
            meant installing a native application, creating a custodial account,
            backing up keys, or writing down a seed phrase. VeryGoodWallet starts
            with something you may already have: a synced, phishing-resistant
            passkey.
          </p>
          <p>
            On supported authenticators, WebAuthn&apos;s <code>prf</code> extension
            gives the wallet the same secret material whenever you authenticate.
            The wallet passes that through HKDF to derive the keys it needs:
          </p>
          <pre>
            <code>{`passkey PRF output
  └─ HKDF
      ├─ vault key      AES-GCM over everything stored at rest
      ├─ link secret    one secret for life, blind-committed into
      │                 every credential, no issuer ever sees it
      └─ issuance keys  one per issuer, for request freshness only`}</code>
          </pre>
          <p>
            The passkey is more than a login mechanism. It is the root of the
            wallet&apos;s key hierarchy. The derived keys live only in memory while
            the wallet is unlocked, credentials are encrypted in the browser, and
            locking the wallet clears the key material. Recovery follows the
            passkey&apos;s existing synchronization model, such as iCloud Keychain or
            Google Password Manager. The link secret in the middle of that tree
            is what binds a credential to its holder — it returns several times
            in this article.
          </p>
          <p>
            With a wallet and a signed credential in it, two problems appear
            immediately, and they shape everything that follows. With a typical
            digital signature:
          </p>
          <ul>
            <li>
              <strong>You have to show everything.</strong> The signature covers
              the whole document, so removing one field breaks it. Proving that
              you are over 18 means sharing your name, address, and exact birthday
              too, which is the same problem you have with a physical ID card.
            </li>
            <li>
              <strong>Presentations can be linked.</strong> If the same signature
              is shown in two places, the bytes match. Two verifiers can compare
              them and connect their records, even if you shared different fields
              with each one. The issuer can recognize its own signature too.
            </li>
          </ul>
          <p>
            The question, then, is whether you can prove that an issuer signed
            your credential without showing the whole thing or giving verifiers
            something they can compare later. That is the question the rest of
            this article answers.
          </p>

          <h3 id="credential-anatomy">The anatomy of a credential</h3>
          <p>
            Before the how, it helps to look closely at the what. Below is the
            license the demo DMV issues — a real signed document produced by the
            demo&apos;s own stack, with only the long strings shortened. The
            highlights are the parts the rest of the article keeps returning to.
          </p>
          <CredentialAnatomy />

          <h2 id="bbs">BBS signatures, explained</h2>
          <p>
            The proof block at the bottom of the license names the signature
            scheme: BBS, after Boneh, Boyen, and Shacham, whose 2004 work on
            group signatures it grew out of. It is now being standardized in an{" "}
            <a href="https://datatracker.ietf.org/doc/draft-irtf-cfrg-bbs-signatures/">
              IETF draft
            </a>
            . Two properties separate it from the signatures the web already runs
            on, like ECDSA or Ed25519.
          </p>
          <p>
            First, <strong>BBS signs a list of messages, not one blob</strong>.
            The wallet&apos;s processing turns the license into a list of
            statements — one per field, roughly — and the DMV signs the list.
            Figure 1&apos;s license becomes 32 signed slots: 28 statements from
            the document, two hidden numeric twins, and the blind-committed link
            secret with its blinding factor. The signature is 80 bytes no matter
            how long the list gets.
          </p>
          <p>
            Second, <strong>the signature itself is never shown to anyone</strong>.
            The wallet keeps it. What a verifier receives instead is a{" "}
            <em>proof</em>: a freshly randomized demonstration that the wallet
            holds a valid DMV signature over the full list, which reveals exactly
            the messages you choose and nothing about the rest. The verifier
            learns that the hidden messages were signed, but not what they say.
          </p>
          <p>This one change of habit buys two properties:</p>
          <ul>
            <li>
              <strong>Selective disclosure.</strong> Reveal a birth date to one
              verifier and only an over-18 result to another, all from the same
              credential. The wallet&apos;s consent screen is where that choice is
              made.
            </li>
            <li>
              <strong>Unlinkability.</strong> Each proof is built from new
              randomness, so two presentations of the same credential share no
              bytes a pair of verifiers could match. The only possible overlap
              comes from values you choose to disclose in both places.
            </li>
          </ul>
          <div className="aside">
            <p className="aside-label">For the cryptographically inclined</p>
            <p>
              A BBS-derived proof is a zero-knowledge proof of knowledge of the
              signature: a sigma protocol with the same commit, challenge, and
              response steps as Schnorr identification, made non-interactive by
              hashing the transcript with Fiat–Shamir. The arithmetic is pairings
              on BLS12-381. There is no circuit compiler, no proving key, and no
              setup ceremony — which is a large part of why all of it runs in
              plain TypeScript.
            </p>
          </div>

          <h3 id="holder-binding">Whose credential is it, then?</h3>
          <p>
            Unlinkability comes with a discipline: it is only as good as what you
            disclose. If an issuer writes a holder identifier such as{" "}
            <code>credentialSubject.id</code> into the document, that identifier
            surfaces in every presentation and links them all. That is why figure
            1&apos;s subject has no <code>id</code> — the DMV deliberately issues
            no DID, public key, or <code>holder</code> property.
          </p>
          <p>
            But if the credential does not identify its holder, what stops
            someone else from presenting a stolen copy? This is where the link
            secret from the key tree comes in. At issuance, the wallet sends the
            DMV a <em>commitment</em> to its lifelong link secret, along with
            proof that the wallet knows the secret behind it. Following the
            IETF&apos;s blind BBS extension, the DMV signs that committed value
            into the credential without ever seeing the secret itself — it is one
            of the 32 slots under figure 1&apos;s signature.
          </p>
          <p>
            From then on, every presentation proves that the presenter knows the
            same hidden secret, without revealing an identifier — not even a
            pairwise one. And because the wallet commits the <em>same</em> secret
            into every credential it collects, it can also prove that two
            credentials belong to the same holder — a choice the presentation
            section returns to.
          </p>

          <h2 id="presentations">What a presentation can prove</h2>
          <p>
            Everything so far ends in the same act: the wallet assembles a{" "}
            <em>presentation</em> for one verifier, for one session. Selective
            disclosure — revealing some fields and hiding others — is the
            simplest thing a presentation can do. The demo&apos;s presentations
            can make three stronger kinds of statement, all about values that
            stay hidden.
          </p>
          <p>
            <strong>Range proofs</strong> prove an inequality about a hidden
            number. When the DMV issues a license, it encodes the birth date as a
            number — days since 1900 — and signs that hidden twin alongside the
            readable date. At presentation time the verifier picks a cutoff, and
            the wallet proves <code>birth_date ≤ cutoff</code> against the twin.
            Earlier birth dates are smaller numbers, so &quot;at least 18&quot;
            is one comparison. The Nightcap checks an 18-year cutoff; Utopia
            Wheels checks 25 against the very same credential. Contrast that with
            the license&apos;s <code>age_over_18/21/25</code> flags, which were
            frozen at issuance: flags can only answer the questions the issuer
            anticipated, while a range proof takes any cutoff, live. For the
            demo&apos;s under-18 persona, the wallet simply cannot construct the
            proof — there is no way to lie with it.
          </p>
          <p>
            <strong>Membership proofs</strong> prove that a hidden number belongs
            to a set the verifier publishes. The Utopia Resident Registration
            carries a numeric district code as a hidden twin, and a proof can
            show the code is one of the coastal districts without revealing which
            one.
          </p>
          <p>
            <strong>Equality proofs</strong> prove that two hidden values are the
            same — the load-bearing case being the link secret shared by every
            credential in the wallet, which is how two credentials are shown to
            have one holder.
          </p>
          <p>
            One safeguard applies to all of these: each verifier publishes its
            proof parameters at a well-known URL, and the wallet checks their
            hash before proving. Otherwise a verifier could hand slightly
            different parameters to each visitor and use them as tags.
          </p>
          <div className="aside">
            <p className="aside-label">For the cryptographically inclined</p>
            <p>
              The range and membership proofs are the 2008
              Camenisch–Chaabouni–Shelat construction — the hidden value is
              decomposed into base-16 digits, each proven to lie in the
              verifier&apos;s signed alphabet — and they live in the same
              sigma-protocol family as the BBS proof. Every predicate shares one
              Fiat–Shamir transcript with the credential proofs, which is what
              ties each claim to the exact signed hidden value it speaks about.
            </p>
          </div>

          <h3 id="linking">Linking as a choice</h3>
          <p>
            Presentations are unlinkable by default, but sometimes the holder{" "}
            <em>wants</em> to prove a connection. Utopia Wheels&apos;
            resident-rate discount needs three facts: the customer is over 25,
            lives in a coastal district, and holds both credentials. You could
            prove that last part by disclosing a name from each credential and
            letting the clerk squint. This demo does it without sharing anything:
          </p>
          <PresentationCards />
          <p>
            The wallet combines all three checks in a single presentation. The
            equality proof confirms that both credentials hide the same link
            secret — possible because the wallet committed the same
            passkey-derived secret into each one at issuance. The verifier learns
            the intended results and nothing else, and it cannot discover the
            connection later from presentations made separately: the holder
            chooses when the link is provable.
          </p>

          <h3 id="presentation-anatomy">The anatomy of a presentation</h3>
          <p>
            Here is what actually leaves the wallet for that rental-counter
            check — the entire response body, reduced only where marked. It is
            worth comparing the embedded license against figure 1: the document
            that crosses the wire is mostly absence.
          </p>
          <PresentationWire />

          <h3 id="verifier-compare">What two verifiers can compare</h3>
          <p>
            The wallet keeps an encrypted log of every presentation, and at the
            end of the demo it lays out what each verifier received side by side.
            The proofs themselves contribute nothing matchable: no holder
            identifier exists, and every proof is freshly randomized. Only values
            deliberately disclosed to both verifiers can overlap. Visit the
            bottle shop with a range proof, then share your name and license
            number only with the rental counter, and their two databases hold no
            common value that connects the records.
          </p>

          <h2 id="revocation">Privacy-preserving revocation</h2>
          <p>
            A private credential still needs a way to stop being valid. Every
            credential the Utopia DMV signs is enrolled in an accumulator-backed
            revocation registry. The credential carries a fresh revocation id as
            a permanently hidden signed value — figure 1&apos;s{" "}
            <code>credentialStatus</code> — while the wallet keeps a separate
            membership witness showing that the id belongs to the issuer&apos;s
            current unrevoked set.
          </p>
          <p>
            When the DMV revokes a credential, the registry publishes a new epoch
            and public update records. Every non-revoked wallet can update its
            witness from the same published data. The wallet downloads the
            registry state as a whole, so the registry does not learn which
            credential is asking.
          </p>
          <p>
            During presentation, the verifier requires a non-revocation proof
            against the registry state it trusts — the two 128-byte segments in
            figure 3. That proof is bound to the credential proofs and the rest
            of the presentation under the same challenge. The verifier learns
            exactly one fact, that the credential is still valid, and never sees
            the hidden revocation id or which registry entry produced the proof.
          </p>

          <h2 id="browser">The browser is part of the thesis</h2>
          <p>
            VeryGoodWallet is partly an identity experiment and partly a
            browser-cryptography experiment. The wallet is a static browser
            application: its keys are derived locally from the passkey, its
            credentials stay encrypted locally, and every proof in this article —
            BBS, range, membership, equality, non-revocation — is constructed on
            the holder&apos;s side, in the browser, in plain TypeScript. No
            native library, no WASM build, no SNARK runtime, and no wallet
            backend ever receives a private credential.
          </p>
          <p>
            The demo still has issuer and verifier services, because credential
            protocols require counterparties with session state, trust policy,
            and registries — Cloudflare Workers, here. But the cryptography is
            not tied to a privileged environment: credkit runs identically in the
            wallet&apos;s browser tab and in a verifier&apos;s Worker, so where
            verification happens is an architectural choice rather than a
            limitation of the proof system.
          </p>

          <h2 id="standards">How it fits with existing standards</h2>
          <p>
            The demo brings these privacy features to protocols and formats that
            are already used for verifiable credentials:
          </p>
          <ul>
            <li>
              <strong>OpenID for Verifiable Credential Issuance (OID4VCI).</strong>{" "}
              The DMV uses the pre-authorized code flow. The holder-binding
              commitment is an extension field in the credential request,
              alongside the standard proof-of-possession JWT.
            </li>
            <li>
              <strong>
                OpenID for Verifiable Presentations (OID4VP) with DCQL.
              </strong>{" "}
              Verifiers make requests in the standard query language. Predicate,
              linkage, and non-revocation requirements are small, documented
              extensions. Requests are passed by reference to keep QR codes
              scannable, responses return through <code>direct_post</code>, and
              each proof is bound to the request&apos;s one-time nonce and the
              verifier&apos;s identity so it cannot be replayed somewhere else —
              figure 3&apos;s <code>challenge</code> and <code>domain</code>.
            </li>
            <li>
              <strong>W3C Verifiable Credentials.</strong> Credentials are VC Data
              Model 2.0 documents with Data Integrity proofs, using standard
              JSON-LD processing and envelopes.
            </li>
            <li>
              <strong>IETF BBS.</strong> The signature core implements the CFRG BBS
              draft and its blind-issuance companion. The implementation is
              checked against the drafts&apos; published test fixtures.
            </li>
          </ul>
          <p>
            There is one important exception: the cryptosuite itself is
            experimental. The W3C&apos;s candidate BBS suite, <code>bbs-2023</code>,
            supports selective disclosure, but not predicates, multi-credential
            presentations, or a link secret. This demo uses{" "}
            <code>credkit-bbs-sha-2026</code>, an experimental Data Integrity suite
            from <a href="https://github.com/tmarkovski/credkit">credkit</a>, a
            companion project of mine.
          </p>
          <p>
            People who have worked with earlier privacy-preserving credential
            systems will recognize many of these goals. Some of those systems,
            including AnonCreds, were an important part of my own history in this
            field. Credkit approaches the problem through today&apos;s BBS, Verifiable
            Credential, OpenID4VC, passkey, and browser ecosystem.
          </p>
          <p>
            Credkit keeps <code>bbs-2023</code>&apos;s document pipeline, including
            canonicalization, selection, and mandatory pointers, and replaces the
            proof layer with the composite construction described above. Its
            identifiers are deliberately distinct, and a{" "}
            <a href="https://tmarkovski.github.io/credkit/">
              draft specification
            </a>{" "}
            documents the construction.
          </p>
          <p>
            It is research work, not a standard. The proofs use the same commit,
            challenge, and response phases and the same disciplined transcript
            that the CFRG&apos;s emerging{" "}
            <a href="https://datatracker.ietf.org/doc/draft-irtf-cfrg-sigma-protocols/">
              sigma-protocols
            </a>{" "}
            and{" "}
            <a href="https://datatracker.ietf.org/doc/draft-irtf-cfrg-fiat-shamir/">
              Fiat-Shamir
            </a>{" "}
            drafts describe. What those drafts do not yet cover, composing several
            statements under one challenge, is the gap the credkit draft
            documents.
          </p>
          <p className="spec-credit">
            None of this would exist without the people behind the drafts it
            builds on: Tobias Looker, Vasilis Kalos, Andrew Whitehead, and Mike
            Lodder on the{" "}
            <a href="https://datatracker.ietf.org/doc/draft-irtf-cfrg-bbs-signatures/">
              core BBS specification
            </a>
            , and Vasilis Kalos and Greg M. Bernstein on the{" "}
            <a href="https://datatracker.ietf.org/doc/draft-irtf-cfrg-bbs-blind-signatures/">
              blind BBS specification
            </a>
            . Thanks as well to the wider CFRG community that helped move both
            forward.
          </p>

          <h2 id="real">What is real and what remains experimental</h2>
          <p>
            VeryGoodWallet is a real implementation, not a clickable mockup. The
            issuer signs credentials. The wallet encrypts and stores them.
            OpenID4VCI and OpenID4VP move them between parties. The wallet
            constructs real zero-knowledge proofs, and the verifier checks them.
            Credentials can be revoked, witnesses can be updated from published
            registry records, and non-revocation is enforced during presentation.
            The specimens in figures 1 and 3 came from running that stack, not
            from an illustration tool.
          </p>
          <p>But it is not a production wallet.</p>
          <ul>
            <li>
              <strong>It is research software.</strong> Neither credkit nor this
              site has been independently audited. The custom proof and
              cryptosuite layers do not have an independent implementation or
              external interoperability test suite.
            </li>
            <li>
              <strong>Issuer trust starts with TLS.</strong> The verifiers pin the
              DMV&apos;s DID from its metadata endpoint. A production system would
              need <code>did:web</code> or a trust registry.
            </li>
            <li>
              <strong>Privacy still has edges.</strong> Information the holder
              deliberately discloses can still be compared. Credential validity
              windows create a small correlation surface, and registry access
              needs appropriate caching and distribution to reduce timing signals.
            </li>
            <li>
              <strong>Losing every copy of the passkey means losing the wallet.</strong>{" "}
              Passkey sync is the recovery mechanism, so the wallet depends on it.
            </li>
            <li>
              <strong>The cast is fictional.</strong> The State of Utopia issues no
              real licenses, the shop sells nothing, and the rental fleet is six
              SVGs. The cryptography and protocols are real.
            </li>
          </ul>

          <h2 id="vision">A vision I have carried with me</h2>
          <p>
            I built VeryGoodWallet and much of credkit over a couple of weekends,
            with modern coding models helping me explore, implement, test, and
            document the system at a pace that would have been hard to imagine
            when I first entered this space.
          </p>
          <p>
            The mathematics behind many of these ideas is not new. The privacy
            goals are not new. What has changed is how accessible the pieces have
            become, and how quickly one person can now turn a long-held
            architecture into running software.
          </p>
          <p>
            I do not see VeryGoodWallet as the finished answer to digital identity.
            It is research software, and there is plenty here that deserves
            scrutiny. But it is the first time I have been able to put this
            particular idea together in the form I originally imagined: a wallet
            managed by something people already use, credentials exchanged through
            recognizable protocols, and privacy-preserving proofs running directly
            in an ordinary web environment.
          </p>
          <p>
            For me, it feels like finally exploring the wallet vision that first
            excited me about this space with tools that can now do it justice.
          </p>

          <h2 id="colophon">Colophon</h2>
          <p>
            The project is a pnpm monorepo built with React, Vite, and Tailwind on
            Cloudflare Workers&apos; free tier. The Worker APIs use Hono, and
            verification sessions live in SQLite-backed Durable Objects. Credkit
            handles the BBS core, range and membership proofs, accumulator
            revocation, composite presentations, and the JSON-LD cryptosuite in
            pure TypeScript over BLS12-381. WebAuthn PRF and HKDF provide the key
            hierarchy, with no WASM anywhere. Every major flow has unit,
            integration, and live end-to-end tests. Source:{" "}
            <a href="https://github.com/tmarkovski/verygoodwallet">
              github.com/tmarkovski/verygoodwallet
            </a>{" "}
            and <a href="https://github.com/tmarkovski/credkit">
              github.com/tmarkovski/credkit
            </a>
            .
          </p>
        </article>
      </div>

      <aside className="hidden pt-12 lg:block">
        <Toc sections={TOC_SECTIONS} />
      </aside>
    </div>
  );
}
